import dash
import dash_core_components as dcc 
import dash_html_components as html
import dash_daq as daq 
import plotly.graph_objs as go 
from dash.dependencies import Input, Output, State
import pandas as pd 
import pickle 

############ Initiate the app
external_stylesheets = ['https://codepen.io/chriddyp/pen/bWLwgP.css']
app = dash.Dash(__name__, external_stylesheets=external_stylesheets)
app.config.suppress_callback_exceptions = True
server = app.server
app.title='top20gbc'

########### Setup the layout
app.layout = html.Div(children=[
    html.H1('Make It Top 20!'),
    html.Div([
        html.H6('Key Signature'),
        daq.Knob(
            id='key_knob',
            min=0,
            max=15,
            value=5,
            scale={'start':0, 'interval':1, 'labelInterval':5}
        ),
        html.Br(),

        html.H6('Loudness'),
        daq.Knob(
            id='loud_knob',
            min=-40,
            max=0,
            value=-9,
            scale={'start':-40, 'interval':5, 'labelInterval':1}
        ),
        html.Br(),

        html.H6('Tempo'),
        daq.Knob(
            id='tempo_knob',
            min=0,
            max=300,
            value=125,
            scale={'start':0, 'interval':20, 'labelInterval':1}
        ),
        html.Br(),

        html.H6('Time Signature Confidence'),
        daq.Knob(
            id='time_knob',
            min=0,
            max=1,
            value=0.5,
            scale={'start':0, 'interval':0.1, 'labelInterval':1}
        ),
        html.Br(),
        
        html.H6('Mode Confidence'),
        daq.Knob(
            id='mode_knob',
            min=0,
            max=1,
            value=0.4,
            scale={'start':0, 'interval':0.1, 'labelInterval':1}
        ),
        html.Br(),
        
        html.H6('Artist Familiartiy'),
        daq.Knob(
            id='familiar_knob',
            min=0,
            max=1,
            value=0.7,
            scale={'start':0, 'interval':0.1, 'labelInterval':1}
        ),
        html.Br(),
        
        html.H6('Artist Hotness'),
        daq.Knob(
            id='hot_knob',
            min=0,
            max=1,
            value=0.5,
            scale={'start':0, 'interval':0.1, 'labelInterval':1}
        ),
        html.Br(),

        html.H6('Fade In'),
        daq.Knob(
            id='in_knob',
            min=0,
            max=40,
            value=2,
            scale={'start':0, 'interval':5, 'labelInterval':1}
        ),
        html.Br(),

        html.H6('Fade Out'),
        daq.Knob(
            id='out_knob',
            min=0,
            max=1600,
            value=235,
            scale={'start':0, 'interval':100, 'labelInterval':1}
        ),

    
        html.H6('Year'),
        dcc.Dropdown(
            id='year_drop',
            options=[
                {'label': 1900, 'value': 1900},
 {'label': 1901, 'value': 1901},
 {'label': 1902, 'value': 1902},
 {'label': 1903, 'value': 1903},
 {'label': 1904, 'value': 1904},
 {'label': 1905, 'value': 1905},
 {'label': 1906, 'value': 1906},
 {'label': 1907, 'value': 1907},
 {'label': 1908, 'value': 1908},
 {'label': 1909, 'value': 1909},
 {'label': 1910, 'value': 1910},
 {'label': 1911, 'value': 1911},
 {'label': 1912, 'value': 1912},
 {'label': 1913, 'value': 1913},
 {'label': 1914, 'value': 1914},
 {'label': 1915, 'value': 1915},
 {'label': 1916, 'value': 1916},
 {'label': 1917, 'value': 1917},
 {'label': 1918, 'value': 1918},
 {'label': 1919, 'value': 1919},
 {'label': 1920, 'value': 1920},
 {'label': 1921, 'value': 1921},
 {'label': 1922, 'value': 1922},
 {'label': 1923, 'value': 1923},
 {'label': 1924, 'value': 1924},
 {'label': 1925, 'value': 1925},
 {'label': 1926, 'value': 1926},
 {'label': 1927, 'value': 1927},
 {'label': 1928, 'value': 1928},
 {'label': 1929, 'value': 1929},
 {'label': 1930, 'value': 1930},
 {'label': 1931, 'value': 1931},
 {'label': 1932, 'value': 1932},
 {'label': 1933, 'value': 1933},
 {'label': 1934, 'value': 1934},
 {'label': 1935, 'value': 1935},
 {'label': 1936, 'value': 1936},
 {'label': 1937, 'value': 1937},
 {'label': 1938, 'value': 1938},
 {'label': 1939, 'value': 1939},
 {'label': 1940, 'value': 1940},
 {'label': 1941, 'value': 1941},
 {'label': 1942, 'value': 1942},
 {'label': 1943, 'value': 1943},
 {'label': 1944, 'value': 1944},
 {'label': 1945, 'value': 1945},
 {'label': 1946, 'value': 1946},
 {'label': 1947, 'value': 1947},
 {'label': 1948, 'value': 1948},
 {'label': 1949, 'value': 1949},
 {'label': 1950, 'value': 1950},
 {'label': 1951, 'value': 1951},
 {'label': 1952, 'value': 1952},
 {'label': 1953, 'value': 1953},
 {'label': 1954, 'value': 1954},
 {'label': 1955, 'value': 1955},
 {'label': 1956, 'value': 1956},
 {'label': 1957, 'value': 1957},
 {'label': 1958, 'value': 1958},
 {'label': 1959, 'value': 1959},
 {'label': 1960, 'value': 1960},
 {'label': 1961, 'value': 1961},
 {'label': 1962, 'value': 1962},
 {'label': 1963, 'value': 1963},
 {'label': 1964, 'value': 1964},
 {'label': 1965, 'value': 1965},
 {'label': 1966, 'value': 1966},
 {'label': 1967, 'value': 1967},
 {'label': 1968, 'value': 1968},
 {'label': 1969, 'value': 1969},
 {'label': 1970, 'value': 1970},
 {'label': 1971, 'value': 1971},
 {'label': 1972, 'value': 1972},
 {'label': 1973, 'value': 1973},
 {'label': 1974, 'value': 1974},
 {'label': 1975, 'value': 1975},
 {'label': 1976, 'value': 1976},
 {'label': 1977, 'value': 1977},
 {'label': 1978, 'value': 1978},
 {'label': 1979, 'value': 1979},
 {'label': 1980, 'value': 1980},
 {'label': 1981, 'value': 1981},
 {'label': 1982, 'value': 1982},
 {'label': 1983, 'value': 1983},
 {'label': 1984, 'value': 1984},
 {'label': 1985, 'value': 1985},
 {'label': 1986, 'value': 1986},
 {'label': 1987, 'value': 1987},
 {'label': 1988, 'value': 1988},
 {'label': 1989, 'value': 1989},
 {'label': 1990, 'value': 1990},
 {'label': 1991, 'value': 1991},
 {'label': 1992, 'value': 1992},
 {'label': 1993, 'value': 1993},
 {'label': 1994, 'value': 1994},
 {'label': 1995, 'value': 1995},
 {'label': 1996, 'value': 1996},
 {'label': 1997, 'value': 1997},
 {'label': 1998, 'value': 1998},
 {'label': 1999, 'value': 1999},
 {'label': 2000, 'value': 2000},
 {'label': 2001, 'value': 2001},
 {'label': 2002, 'value': 2002},
 {'label': 2003, 'value': 2003},
 {'label': 2004, 'value': 2004},
 {'label': 2005, 'value': 2005},
 {'label': 2006, 'value': 2006},
 {'label': 2007, 'value': 2007},
 {'label': 2008, 'value': 2008},
 {'label': 2009, 'value': 2009},
 {'label': 2010, 'value': 2010},
 {'label': 2011, 'value': 2011},
 {'label': 2012, 'value': 2012},
 {'label': 2013, 'value': 2013},
 {'label': 2014, 'value': 2014},
 {'label': 2015, 'value': 2015},
 {'label': 2016, 'value': 2016},
 {'label': 2017, 'value': 2017},
 {'label': 2018, 'value': 2018},
 {'label': 2019, 'value': 2019},
 {'label': 2020, 'value': 2020}
            ],
            value=1995,
            style={
                'height':'2px',
                'width':'100px',
                'min-height':'1px',
            }
        ),
        html.Br(),

        html.H6('Location'),
        dcc.Dropdown(
            id='location_drop',
            options=[{'label': 'Tacoma WA', 'value': 'Tacoma WA'},
 {'label': 'Anderson IN', 'value': 'Anderson IN'},
 {'label': 'Cross Lane WV', 'value': 'Cross Lane WV'},
 {'label': 'Boston MA', 'value': 'Boston MA'},
 {'label': 'Chicago IL', 'value': 'Chicago IL'},
 {'label': 'Menilmontant France', 'value': 'Menilmontant France'},
 {'label': 'Cleveland OH', 'value': 'Cleveland OH'},
 {'label': 'St. Louis MO', 'value': 'St. Louis MO'},
 {'label': 'Essex England', 'value': 'Essex England'},
 {'label': 'London England', 'value': 'London England'},
 {'label': 'Couchman TX', 'value': 'Couchman TX'},
 {'label': 'Newton-le-Willows Merseyside England',
  'value': 'Newton-le-Willows Merseyside England'},
 {'label': 'St. Joseph MO', 'value': 'St. Joseph MO'},
 {'label': 'SPRINGFIELD Virginia', 'value': 'SPRINGFIELD Virginia'},
 {'label': 'Shelby North Carolina', 'value': 'Shelby North Carolina'},
 {'label': 'Cardiff Wales', 'value': 'Cardiff Wales'},
 {'label': 'Brenham TX', 'value': 'Brenham TX'},
 {'label': 'Heston Middlesex England', 'value': 'Heston Middlesex England'},
 {'label': 'Montego Bay Jamaica', 'value': 'Montego Bay Jamaica'},
 {'label': 'Berlin Germany', 'value': 'Berlin Germany'},
 {'label': 'Tulsa Oklahoma', 'value': 'Tulsa Oklahoma'},
 {'label': 'Berkeley CA', 'value': 'Berkeley CA'},
 {'label': 'Wales', 'value': 'Wales'},
 {'label': 'Sacramento CA', 'value': 'Sacramento CA'},
 {'label': 'New York NY', 'value': 'New York NY'},
 {'label': 'Los Angeles CA', 'value': 'Los Angeles CA'},
 {'label': 'Puerto Rico', 'value': 'Puerto Rico'},
 {'label': 'California - LA', 'value': 'California - LA'},
 {'label': 'Hughesdale Victoria Australia',
  'value': 'Hughesdale Victoria Australia'},
 {'label': 'Talladega AL', 'value': 'Talladega AL'},
 {'label': 'Lynn Lake Manitoba Canada', 'value': 'Lynn Lake Manitoba Canada'},
 {'label': 'San Francisco CA', 'value': 'San Francisco CA'},
 {'label': 'Seattle WA', 'value': 'Seattle WA'},
 {'label': 'Ponchatoula LA', 'value': 'Ponchatoula LA'},
 {'label': 'Hanna Alberta Canada', 'value': 'Hanna Alberta Canada'},
 {'label': 'Jamaica', 'value': 'Jamaica'},
 {'label': 'Sevenoaks United Kingdom', 'value': 'Sevenoaks United Kingdom'},
 {'label': 'Aberdeen', 'value': 'Aberdeen'},
 {'label': 'Oslo Norway', 'value': 'Oslo Norway'},
 {'label': 'Melbourne', 'value': 'Melbourne'},
 {'label': 'Marvell AR', 'value': 'Marvell AR'},
 {'label': 'New York NY [The Bronx]', 'value': 'New York NY [The Bronx]'},
 {'label': 'Dublin Ireland', 'value': 'Dublin Ireland'},
 {'label': 'Stillwater OK', 'value': 'Stillwater OK'},
 {'label': 'Jackson MS', 'value': 'Jackson MS'},
 {'label': 'Chapel Hill NC', 'value': 'Chapel Hill NC'},
 {'label': 'Washington England', 'value': 'Washington England'},
 {'label': 'SANTA ANA California', 'value': 'SANTA ANA California'},
 {'label': 'United Kingdom', 'value': 'United Kingdom'},
 {'label': 'Lancaster NH', 'value': 'Lancaster NH'},
 {'label': 'allentown Pennsylvania USA',
  'value': 'allentown Pennsylvania USA'},
 {'label': 'Brooklyn NY', 'value': 'Brooklyn NY'},
 {'label': 'Glasgow Scotland', 'value': 'Glasgow Scotland'},
 {'label': 'Seattle Washington', 'value': 'Seattle Washington'},
 {'label': 'Dundee Scotland', 'value': 'Dundee Scotland'},
 {'label': 'Staunton VA', 'value': 'Staunton VA'},
 {'label': 'Hermosa Beach CA', 'value': 'Hermosa Beach CA'},
 {'label': 'Escatawpa MS', 'value': 'Escatawpa MS'},
 {'label': 'London', 'value': 'London'},
 {'label': 'Sch�erg Germany', 'value': 'Sch�erg Germany'},
 {'label': 'Brussels Belgium', 'value': 'Brussels Belgium'},
 {'label': 'oxford', 'value': 'oxford'},
 {'label': 'Bay City MI', 'value': 'Bay City MI'},
 {'label': 'London / Ex-Manchester', 'value': 'London / Ex-Manchester'},
 {'label': 'Laredo TX', 'value': 'Laredo TX'},
 {'label': 'Orlando FL', 'value': 'Orlando FL'},
 {'label': 'Nueva Jersey (Estados Unidos)',
  'value': 'Nueva Jersey (Estados Unidos)'},
 {'label': 'England', 'value': 'England'},
 {'label': 'New Jersey', 'value': 'New Jersey'},
 {'label': 'Minnesota', 'value': 'Minnesota'},
 {'label': 'Bridgend South Wales UK', 'value': 'Bridgend South Wales UK'},
 {'label': 'Charlottesville VA', 'value': 'Charlottesville VA'},
 {'label': 'Vermillion SD', 'value': 'Vermillion SD'},
 {'label': 'Sydney Australia', 'value': 'Sydney Australia'},
 {'label': 'United States', 'value': 'United States'},
 {'label': 'Poway CA', 'value': 'Poway CA'},
 {'label': 'Minneapolis MN', 'value': 'Minneapolis MN'},
 {'label': 'Memphis Tennessee', 'value': 'Memphis Tennessee'},
 {'label': 'Detroit MI', 'value': 'Detroit MI'},
 {'label': 'Birmingham England', 'value': 'Birmingham England'},
 {'label': 'Paddington London England', 'value': 'Paddington London England'},
 {'label': 'Austin TX', 'value': 'Austin TX'},
 {'label': 'New York', 'value': 'New York'},
 {'label': 'Texas', 'value': 'Texas'},
 {'label': 'Long Island NY', 'value': 'Long Island NY'},
 {'label': 'Queensbridge NY', 'value': 'Queensbridge NY'},
 {'label': 'Kitee Finland', 'value': 'Kitee Finland'},
 {'label': 'Paris France', 'value': 'Paris France'},
 {'label': 'Kentwood LA; Los Angeles CA',
  'value': 'Kentwood LA; Los Angeles CA'},
 {'label': 'Seymour IN', 'value': 'Seymour IN'},
 {'label': 'Aberdeen Scotland', 'value': 'Aberdeen Scotland'},
 {'label': 'Helsinki Finland', 'value': 'Helsinki Finland'},
 {'label': 'Brownsville TX', 'value': 'Brownsville TX'},
 {'label': 'Stockholm', 'value': 'Stockholm'},
 {'label': 'Sheffield South Yorkshire Engla',
  'value': 'Sheffield South Yorkshire Engla'},
 {'label': 'Barranquilla Colombia', 'value': 'Barranquilla Colombia'},
 {'label': 'Harlem New York', 'value': 'Harlem New York'},
 {'label': 'UK - England - Yorkshire', 'value': 'UK - England - Yorkshire'},
 {'label': 'Germany', 'value': 'Germany'},
 {'label': 'PHILADELPHIA Pennsylvania', 'value': 'PHILADELPHIA Pennsylvania'},
 {'label': 'Virginia', 'value': 'Virginia'},
 {'label': 'Ipswich England', 'value': 'Ipswich England'},
 {'label': 'Charlotte NC', 'value': 'Charlotte NC'},
 {'label': 'Queens NY', 'value': 'Queens NY'},
 {'label': 'Melbourne Australia', 'value': 'Melbourne Australia'},
 {'label': 'Forest Hills Queens New York City NY USA',
  'value': 'Forest Hills Queens New York City NY USA'},
 {'label': 'Birmingham/ London UK', 'value': 'Birmingham/ London UK'},
 {'label': 'Niteroi Brazil', 'value': 'Niteroi Brazil'},
 {'label': 'Sledge MS', 'value': 'Sledge MS'},
 {'label': 'Antibes France', 'value': 'Antibes France'},
 {'label': 'Arles France', 'value': 'Arles France'},
 {'label': 'Helsinki', 'value': 'Helsinki'},
 {'label': 'East Flatbush Brooklyn NY', 'value': 'East Flatbush Brooklyn NY'},
 {'label': 'Walker-on-Tyne England', 'value': 'Walker-on-Tyne England'},
 {'label': 'Boston', 'value': 'Boston'},
 {'label': 'Speedball', 'value': 'Speedball'},
 {'label': 'Seattle USA', 'value': 'Seattle USA'},
 {'label': 'Chickasaw County MS', 'value': 'Chickasaw County MS'},
 {'label': 'Freehold NJ', 'value': 'Freehold NJ'},
 {'label': 'D�orf Germany', 'value': 'D�orf Germany'},
 {'label': 'Croix-des-Bouquets  Haiti', 'value': 'Croix-des-Bouquets  Haiti'},
 {'label': 'Crawley England', 'value': 'Crawley England'},
 {'label': 'Newark NJ', 'value': 'Newark NJ'},
 {'label': 'Boston Brooklyn USA', 'value': 'Boston Brooklyn USA'},
 {'label': 'Hämeenlinna', 'value': 'Hämeenlinna'},
 {'label': 'Orange County CA', 'value': 'Orange County CA'},
 {'label': 'Bremerton WA', 'value': 'Bremerton WA'},
 {'label': 'POLAND', 'value': 'POLAND'},
 {'label': 'Edmonton Alberta Canada', 'value': 'Edmonton Alberta Canada'},
 {'label': 'Galveston TX', 'value': 'Galveston TX'},
 {'label': 'Oxford UK', 'value': 'Oxford UK'},
 {'label': 'Compton California', 'value': 'Compton California'},
 {'label': 'Galloway Panola County TX', 'value': 'Galloway Panola County TX'},
 {'label': 'Indianapolis IN', 'value': 'Indianapolis IN'},
 {'label': 'NY - New York City', 'value': 'NY - New York City'},
 {'label': 'East Orange NJ', 'value': 'East Orange NJ'},
 {'label': 'Amherst MA', 'value': 'Amherst MA'},
 {'label': 'Cambridgeshire England', 'value': 'Cambridgeshire England'},
 {'label': 'Port Elizabeth South Africa',
  'value': 'Port Elizabeth South Africa'},
 {'label': 'Teoc MS', 'value': 'Teoc MS'},
 {'label': 'West London England', 'value': 'West London England'},
 {'label': 'Passaic NJ', 'value': 'Passaic NJ'},
 {'label': 'Dallas TX', 'value': 'Dallas TX'},
 {'label': 'Tennessee', 'value': 'Tennessee'},
 {'label': 'New Orleans LA', 'value': 'New Orleans LA'},
 {'label': 'California - SF', 'value': 'California - SF'},
 {'label': 'Ireland', 'value': 'Ireland'},
 {'label': 'South Jamaica Queens', 'value': 'South Jamaica Queens'},
 {'label': 'Oklahoma City OK', 'value': 'Oklahoma City OK'},
 {'label': 'Brooklyn New York', 'value': 'Brooklyn New York'},
 {'label': 'Boston Massachusettes', 'value': 'Boston Massachusettes'},
 {'label': 'Gore VA', 'value': 'Gore VA'},
 {'label': 'Centerville TX', 'value': 'Centerville TX'},
 {'label': 'Sayreville NJ', 'value': 'Sayreville NJ'},
 {'label': 'M�engladbach Germany', 'value': 'M�engladbach Germany'},
 {'label': 'Toronto Ontario Canada', 'value': 'Toronto Ontario Canada'},
 {'label': 'Vienna', 'value': 'Vienna'},
 {'label': 'Medicine Lodge KS', 'value': 'Medicine Lodge KS'},
 {'label': 'Chuckatuck VA', 'value': 'Chuckatuck VA'},
 {'label': 'Belfast Northern Ireland', 'value': 'Belfast Northern Ireland'},
 {'label': 'Los Angeles Ca', 'value': 'Los Angeles Ca'},
 {'label': 'Goodwill LA', 'value': 'Goodwill LA'},
 {'label': 'İngiltere', 'value': 'İngiltere'},
 {'label': 'Macclesfield Cheshire England',
  'value': 'Macclesfield Cheshire England'},
 {'label': 'Athens GA', 'value': 'Athens GA'},
 {'label': 'Angleterre', 'value': 'Angleterre'},
 {'label': 'Carle Place New York', 'value': 'Carle Place New York'},
 {'label': 'Atlanta GA', 'value': 'Atlanta GA'},
 {'label': 'Oakland CA', 'value': 'Oakland CA'},
 {'label': 'Compton California USA.', 'value': 'Compton California USA.'},
 {'label': 'The Bronx New York', 'value': 'The Bronx New York'},
 {'label': 'DeKalb Illinois USA', 'value': 'DeKalb Illinois USA'},
 {'label': 'Georgia', 'value': 'Georgia'},
 {'label': 'London United Kingdom', 'value': 'London United Kingdom'},
 {'label': 'Newcastle', 'value': 'Newcastle'},
 {'label': 'Ghent Belgium', 'value': 'Ghent Belgium'},
 {'label': 'CANADA - Ontario', 'value': 'CANADA - Ontario'},
 {'label': 'Venice CA', 'value': 'Venice CA'},
 {'label': 'Geneva NY', 'value': 'Geneva NY'},
 {'label': 'Syracuse NY', 'value': 'Syracuse NY'},
 {'label': 'Toyohashi Japan', 'value': 'Toyohashi Japan'},
 {'label': 'Harlem NY', 'value': 'Harlem NY'},
 {'label': 'Rossville Tennessee (Lived in Como Mississippi)',
  'value': 'Rossville Tennessee (Lived in Como Mississippi)'},
 {'label': 'Volos Greece', 'value': 'Volos Greece'},
 {'label': 'Long Beach California', 'value': 'Long Beach California'},
 {'label': 'Chiswick London England', 'value': 'Chiswick London England'},
 {'label': 'Washington D.C.', 'value': 'Washington D.C.'},
 {'label': 'Seattle Washington USA', 'value': 'Seattle Washington USA'},
 {'label': 'Athens Greece', 'value': 'Athens Greece'},
 {'label': 'Lithonia GA', 'value': 'Lithonia GA'},
 {'label': 'Garnant Wales', 'value': 'Garnant Wales'},
 {'label': 'Scotland', 'value': 'Scotland'},
 {'label': 'Bremen Germany', 'value': 'Bremen Germany'},
 {'label': 'LAS VEGAS Nevada', 'value': 'LAS VEGAS Nevada'},
 {'label': 'Nashville TN', 'value': 'Nashville TN'},
 {'label': 'Kingston Jamaica', 'value': 'Kingston Jamaica'},
 {'label': 'Nashville / Los Angeles', 'value': 'Nashville / Los Angeles'},
 {'label': 'J�ping Sweden', 'value': 'J�ping Sweden'},
 {'label': 'Hunington Long Island NY', 'value': 'Hunington Long Island NY'},
 {'label': 'Steubenville OH', 'value': 'Steubenville OH'},
 {'label': 'San Juan Puerto Rico', 'value': 'San Juan Puerto Rico'},
 {'label': 'Earth', 'value': 'Earth'},
 {'label': 'NY - Long Island', 'value': 'NY - Long Island'},
 {'label': 'Kingsland AR', 'value': 'Kingsland AR'},
 {'label': 'Paw Paw WV', 'value': 'Paw Paw WV'},
 {'label': 'Westbury Long Island NY', 'value': 'Westbury Long Island NY'},
 {'label': 'Westmoreland Jamaica', 'value': 'Westmoreland Jamaica'},
 {'label': 'Manchester England', 'value': 'Manchester England'},
 {'label': 'Carcassonne France', 'value': 'Carcassonne France'},
 {'label': 'St. Catherine Jamaica', 'value': 'St. Catherine Jamaica'},
 {'label': 'Oxford MS', 'value': 'Oxford MS'},
 {'label': 'New Haven CT', 'value': 'New Haven CT'},
 {'label': 'Chicago', 'value': 'Chicago'},
 {'label': 'Port Arthur TX', 'value': 'Port Arthur TX'},
 {'label': 'Alabama', 'value': 'Alabama'},
 {'label': 'Los Angeles California', 'value': 'Los Angeles California'},
 {'label': 'Leona Texas', 'value': 'Leona Texas'},
 {'label': 'Hartford CT', 'value': 'Hartford CT'},
 {'label': 'Pasadena CA', 'value': 'Pasadena CA'},
 {'label': 'Richland MS', 'value': 'Richland MS'},
 {'label': 'Mexico City Mexico', 'value': 'Mexico City Mexico'},
 {'label': 'LA / NYC', 'value': 'LA / NYC'},
 {'label': 'Hatfield Hertfordshire England',
  'value': 'Hatfield Hertfordshire England'},
 {'label': 'Beverly Massachusetts', 'value': 'Beverly Massachusetts'},
 {'label': 'Rio de Janeiro Brazil', 'value': 'Rio de Janeiro Brazil'},
 {'label': 'California', 'value': 'California'},
 {'label': 'Ukiah CA', 'value': 'Ukiah CA'},
 {'label': 'Quantico VA', 'value': 'Quantico VA'},
 {'label': 'Ibadan Nigeria', 'value': 'Ibadan Nigeria'},
 {'label': 'Barbados West Indies', 'value': 'Barbados West Indies'},
 {'label': 'Liverpool England', 'value': 'Liverpool England'},
 {'label': 'Muskegon MI', 'value': 'Muskegon MI'},
 {'label': 'Borlänge', 'value': 'Borlänge'},
 {'label': 'Jamestown ND', 'value': 'Jamestown ND'},
 {'label': 'Wilmington NC', 'value': 'Wilmington NC'},
 {'label': 'Pittsburgh PA', 'value': 'Pittsburgh PA'},
 {'label': 'Severn MD', 'value': 'Severn MD'},
 {'label': 'Houston TX', 'value': 'Houston TX'},
 {'label': 'Middlesbrough England', 'value': 'Middlesbrough England'},
 {'label': 'City of Angels', 'value': 'City of Angels'},
 {'label': 'Wangaratta Victoria Australia',
  'value': 'Wangaratta Victoria Australia'},
 {'label': 'Santa Monica CA', 'value': 'Santa Monica CA'},
 {'label': 'Ponce Puerto Rico', 'value': 'Ponce Puerto Rico'},
 {'label': 'Whitby Yorkshire England', 'value': 'Whitby Yorkshire England'},
 {'label': 'Havířov Česká republika', 'value': 'Havířov Česká republika'},
 {'label': 'Nashville Tennessee', 'value': 'Nashville Tennessee'},
 {'label': 'New York New York', 'value': 'New York New York'},
 {'label': 'Harlington TX', 'value': 'Harlington TX'},
 {'label': 'Denver CO', 'value': 'Denver CO'},
 {'label': 'Charlemagne Quebec Canada', 'value': 'Charlemagne Quebec Canada'},
 {'label': 'Lawton OK', 'value': 'Lawton OK'},
 {'label': 'Los Angeles &amp; New York',
  'value': 'Los Angeles &amp; New York'},
 {'label': 'Batley England', 'value': 'Batley England'},
 {'label': 'Edwards MS', 'value': 'Edwards MS'},
 {'label': 'LDN', 'value': 'LDN'},
 {'label': 'Wilmette IL', 'value': 'Wilmette IL'},
 {'label': 'San Antonio TX', 'value': 'San Antonio TX'},
 {'label': 'Barking Essex England', 'value': 'Barking Essex England'},
 {'label': 'Bayshore Long Island NY', 'value': 'Bayshore Long Island NY'},
 {'label': 'Hawaii', 'value': 'Hawaii'},
 {'label': 'Marshville NC', 'value': 'Marshville NC'},
 {'label': 'Lincoln Park MI', 'value': 'Lincoln Park MI'},
 {'label': 'St Michael Barbados ', 'value': 'St Michael Barbados '},
 {'label': 'Chelmsford England', 'value': 'Chelmsford England'},
 {'label': 'Germany (Erfurt Thuringia)',
  'value': 'Germany (Erfurt Thuringia)'},
 {'label': 'S� France', 'value': 'S� France'},
 {'label': 'Gainesville FL', 'value': 'Gainesville FL'},
 {'label': 'Hamburg Germany', 'value': 'Hamburg Germany'},
 {'label': 'Woking Surrey England', 'value': 'Woking Surrey England'},
 {'label': 'Plymouth Devon England', 'value': 'Plymouth Devon England'},
 {'label': 'Whitestone Queens NY', 'value': 'Whitestone Queens NY'},
 {'label': 'Thomson GA', 'value': 'Thomson GA'},
 {'label': 'Vienna Austria', 'value': 'Vienna Austria'},
 {'label': 'Philadelphia PA', 'value': 'Philadelphia PA'},
 {'label': 'Madison Wisconsin', 'value': 'Madison Wisconsin'},
 {'label': 'San Francisco', 'value': 'San Francisco'},
 {'label': 'Lille Nord-Pas-de-Calais France',
  'value': 'Lille Nord-Pas-de-Calais France'},
 {'label': 'Santa Rosa California', 'value': 'Santa Rosa California'},
 {'label': 'Madrid', 'value': 'Madrid'},
 {'label': 'New Mexico', 'value': 'New Mexico'},
 {'label': 'Jacksonville FL', 'value': 'Jacksonville FL'},
 {'label': 'Hernando MS', 'value': 'Hernando MS'},
 {'label': 'New York NY [Bronx]', 'value': 'New York NY [Bronx]'},
 {'label': 'Isle of Wight England', 'value': 'Isle of Wight England'},
 {'label': 'Timişoara', 'value': 'Timişoara'},
 {'label': 'Ann Arbor MI', 'value': 'Ann Arbor MI'},
 {'label': 'Tioga Springs TX', 'value': 'Tioga Springs TX'},
 {'label': 'Hudsonville MS', 'value': 'Hudsonville MS'},
 {'label': 'Sweden', 'value': 'Sweden'},
 {'label': 'Mali Africa', 'value': 'Mali Africa'},
 {'label': 'Las Vegas NV', 'value': 'Las Vegas NV'},
 {'label': 'Hastings England', 'value': 'Hastings England'},
 {'label': 'Braintree Essex England', 'value': 'Braintree Essex England'},
 {'label': 'NL', 'value': 'NL'},
 {'label': 'Napanee Ontario Canada', 'value': 'Napanee Ontario Canada'},
 {'label': 'GERMANY', 'value': 'GERMANY'},
 {'label': 'Locust Ridge TN', 'value': 'Locust Ridge TN'},
 {'label': 'Cairo Egypt', 'value': 'Cairo Egypt'},
 {'label': 'Bakersfield CA', 'value': 'Bakersfield CA'},
 {'label': 'ABD', 'value': 'ABD'},
 {'label': 'Stockholm Sweden', 'value': 'Stockholm Sweden'},
 {'label': 'Gothenburg', 'value': 'Gothenburg'},
 {'label': 'Harlem New York NY', 'value': 'Harlem New York NY'},
 {'label': 'Beverly Hills CA', 'value': 'Beverly Hills CA'},
 {'label': 'Jyväskylä Finland', 'value': 'Jyväskylä Finland'},
 {'label': 'Longjumeau France', 'value': 'Longjumeau France'},
 {'label': 'Mogadishu Somalia', 'value': 'Mogadishu Somalia'},
 {'label': 'Portugal', 'value': 'Portugal'},
 {'label': 'Helsingborg Sweden', 'value': 'Helsingborg Sweden'},
 {'label': 'New York NY [Washington Heights]',
  'value': 'New York NY [Washington Heights]'},
 {'label': 'Greensboro NC', 'value': 'Greensboro NC'},
 {'label': 'The Bronx New York NY', 'value': 'The Bronx New York NY'},
 {'label': 'New York City', 'value': 'New York City'},
 {'label': 'Gilmer TX', 'value': 'Gilmer TX'},
 {'label': 'Madrid Spain', 'value': 'Madrid Spain'},
 {'label': 'Brou-sur-Chantereine France',
  'value': 'Brou-sur-Chantereine France'},
 {'label': 'Lafayette LA', 'value': 'Lafayette LA'},
 {'label': 'HOLLYWOOD California', 'value': 'HOLLYWOOD California'},
 {'label': 'CA', 'value': 'CA'},
 {'label': 'Sao Paulo Brazil', 'value': 'Sao Paulo Brazil'},
 {'label': 'Memphis TN', 'value': 'Memphis TN'},
 {'label': 'Old Town ME', 'value': 'Old Town ME'},
 {'label': 'Buenos Aires.', 'value': 'Buenos Aires.'},
 {'label': 'Morris Plains NJ', 'value': 'Morris Plains NJ'},
 {'label': 'Vernet les Bains', 'value': 'Vernet les Bains'},
 {'label': 'Santa Cruz CA', 'value': 'Santa Cruz CA'},
 {'label': 'Firenze Italy', 'value': 'Firenze Italy'},
 {'label': 'Austin', 'value': 'Austin'},
 {'label': 'El Paso TX', 'value': 'El Paso TX'},
 {'label': 'Centre', 'value': 'Centre'},
 {'label': 'Duluth MN', 'value': 'Duluth MN'},
 {'label': 'Itawamba County MS', 'value': 'Itawamba County MS'},
 {'label': 'Richmond VA', 'value': 'Richmond VA'},
 {'label': 'Rome Italy', 'value': 'Rome Italy'},
 {'label': 'Beaumont Texas', 'value': 'Beaumont Texas'},
 {'label': 'Toronto', 'value': 'Toronto'},
 {'label': 'BEVERLY HILLS California', 'value': 'BEVERLY HILLS California'},
 {'label': 'Fort Myers FL', 'value': 'Fort Myers FL'},
 {'label': 'Bronx NY', 'value': 'Bronx NY'},
 {'label': 'Wyomissing PA', 'value': 'Wyomissing PA'},
 {'label': 'Great Britain / UK', 'value': 'Great Britain / UK'},
 {'label': 'NY', 'value': 'NY'},
 {'label': 'Willowdale Ontario Canada', 'value': 'Willowdale Ontario Canada'},
 {'label': 'New York NY [Queens]', 'value': 'New York NY [Queens]'},
 {'label': 'Timmins Ontario Canada', 'value': 'Timmins Ontario Canada'},
 {'label': 'UK - England - South West', 'value': 'UK - England - South West'},
 {'label': 'Norway', 'value': 'Norway'}],
        value='New York NY [Queens]',
        style={
                'height':'2px',
                'width':'300px',
                'min-height':'1px',
            }
        ),
        html.Br(),
        html.Br(),

        html.H6(id='output-message')

 ]),
    html.Br(),

    html.A('Code on Github', href='https://github.com/HernanDarius/top-20-genre')
])

########### Interactive Callbacks



@app.callback(Output('output-message', 'children'),
            [Input('location_drop','value'),
             Input('key_knob','value'),
             Input('loud_knob','value'),
             Input('tempo_knob', 'value'),
             Input('time_knob','value'),
             Input('year_drop','value'),
             Input('familiar_knob','value'),
             Input('hot_knob','value'),
             Input('in_knob','value'),
             Input('mode_knob','value'),
             Input('out_knob','value')
             ])
def display_results(value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,value11):
    file=open(f'resources/model_gb.pkl','rb')
    model=pickle.load(file)
    file.close()
    new_obs=[[value1,value2,value3,value4,value5,value6,value7,value8,value9,value10,value11]]
    pred=model.predict(new_obs)
    top_20=[True,False]
    final_pred=top_20[pred[0]]
    return f'Is this song in the Top 20 Genres? {final_pred}'


########### Execute the app
if __name__=='__main__':
    app.run_server() 
    